---
  - name: "Setup ArchLinux developing environment"
    become: yes
    hosts: archlinux

    tasks:
    - name: Remove virtualbox nox utils
      community.general.pacman:
        name:
          - virtualbox-guest-utils-nox
        state: absent
        update_cache: true
    - name: Install base packages
      community.general.pacman:
        name:
          - neovim
          - git
          - base-devel
          - zsh
          - xorg-server
          - xorg-xinit
          - xf86-video-vmware
          - i3-wm
          - i3status
          - terminator
          - rofi
          - xsel
          - httpie
          - ripgrep
          - bat
          - exa
          - virtualbox-guest-utils
          - curl
          - sudo
          - fakeroot
          - which
          - make
          - docker
          - docker-compose
          - ttf-jetbrains-mono-nerd
          - noto-fonts-emoji
          - unzip
        state: latest
        update_cache: true
    - name: Enable service docker
      ansible.builtin.service:
        name: docker
        enabled: yes
    - name: Ensure a locale exists
      community.general.locale_gen:
        name: "{{ item }}"
        state: present
      with_items:
        - en_US.UTF-8
        - et_EE.UTF-8
    - name: Enable virtualbox service
      ansible.builtin.service:
        name: vboxservice
        state: started
    - name: Modify sudoers file
      ansible.builtin.copy:
        content: '%wheel ALL=(ALL) NOPASSWD: ALL'
        dest: /etc/sudoers.d/wheel
        mode: '0400'
        owner: root
        group: root
    - name: Add user antti
      ansible.builtin.user:
        name: antti
        password: $6$AGa1f5P0XzaHiqeg$qkhjY9T1FMQPnObqRZOgmfFB7GZym615vn5i1ccV3CpW2NSAOge4zmvwL6H5F43zBKXgMoWfLJoAsj6Ku2SSE1
        shell: /bin/zsh
        append: yes
        groups: "wheel, docker"
    - name: Remove bashrc
      ansible.builtin.file:
        path: /home/antti/.bashrc
        state: absent
    - name: Remove bash_profile
      ansible.builtin.file:
        path: /home/antti/.bash_profile
        state: absent
    - name: Remove bash_logout
      ansible.builtin.file:
        path: /home/antti/.bash_logout
        state: absent
    - name: Create i3 config directory for antti
      ansible.builtin.file:
        path: /home/antti/.config/i3
        state: directory
        owner: antti
        group: antti
        mode: '0755'
        recurse: yes
    - name: Create terminator config directory for antti
      ansible.builtin.file:
        path: /home/antti/.config/terminator
        state: directory
        owner: antti
        group: antti
        mode: '0755'
        recurse: yes
    - name: Create local bin directory
      ansible.builtin.file:
        path: /home/antti/.local/bin
        state: directory
        owner: antti
        group: antti
        mode: '0755'
    - name: Install config files
      become_user: antti
      git:
        repo: https://github.com/anttilinno/configs.git
        dest: ~/.configfiles
        clone: yes
        update: no
    - name: Get dotfiles
      become_user: antti
      find:
        path: /home/antti/.configfiles/config/dotfiles
        hidden: yes
      register: dotfiles
    - name: Link user dotconfig files
      become_user: antti
      ansible.builtin.file:
        src: "{{ item }}"
        dest: ~/{{ item | basename }}
        owner: antti
        group: antti
        state: link
      with_items: "{{ dotfiles.files | map(attribute='path') }}"
    - name: Link wm config files for user
      become_user: antti
      ansible.builtin.file:
        src: ~/.configfiles/config/i3.config
        dest: ~/.config/i3/config
        owner: antti
        group: antti
        state: link
    - name: Link console config files for user
      become_user: antti
      ansible.builtin.file:
        src: ~/.configfiles/config/terminator_config
        dest: ~/.config/terminator/config
        owner: antti
        group: antti
        state: link
    - name: Link goto for user
      become_user: antti
      ansible.builtin.file:
        src: ~/.configfiles/bin/goto.sh
        dest: ~/.local/bin/goto.sh
        owner: antti
        group: antti
        state: link
    - name: Install Oh-My-Zsh
      become_user: antti
      git:
        repo: https://github.com/robbyrussell/oh-my-zsh.git
        dest: ~/.oh-my-zsh
        clone: yes
      register: oh_my_zsh_result
    - name: Change default shell to Zsh
      become: yes
      shell: chsh -s $(which zsh) antti
      when: oh_my_zsh_result.changed == true
    - name: Clone yay
      become_user: vagrant
      git:
        repo: https://aur.archlinux.org/yay-bin.git
        dest: "/tmp/yay"
        update: true
    - name: Build and install yay
      become_user: vagrant
      command:
        chdir: "/tmp/yay"
        cmd: "makepkg -sfi --noconfirm"
        creates: /usr/bin/yay
    - name: Check if Librewolf is installed
      stat:
        path: /usr/bin/librewolf
      register: librewolf_exists
    - name: Install Librewolf using yay
      become_user: vagrant
      command:
        cmd: "yay -S --noconfirm librewolf-bin"
      when: not librewolf_exists.stat.exists
