---
  - name: "Setup ArchLinux developing environment"
    become: yes
    hosts: archlinux

    tasks:
    - name: Remove virtualbox nox utils
      community.general.pacman:
        name:
          - virtualbox-guest-utils-nox
        state: absent
        update_cache: true
    - name: Install base packages
      community.general.pacman:
        name:
          - neovim
          - git
          - base-devel
          - zsh
          - xorg-server
          - xorg-xinit
          - xf86-video-vmware
          - i3-wm
          - i3status
          - xfce4-terminal
          - rofi
          - xsel
          - httpie
          - ripgrep
          - bat
          - exa
          - virtualbox-guest-utils
          - curl
          - sudo
          - fakeroot
          - ttf-jetbrains-mono-nerd
          - noto-fonts-emoji
          - unzip
          - lazygit
          - fd
          - btop
          - chezmoi
        state: latest
        update_cache: true
    - name: Ensure a locale exists
      community.general.locale_gen:
        name: "{{ item }}"
        state: present
      with_items:
        - en_US.UTF-8
        - et_EE.UTF-8
    - name: Enable virtualbox service
      ansible.builtin.service:
        name: vboxservice
        state: started
    - name: Modify sudoers file
      ansible.builtin.copy:
        content: '%wheel ALL=(ALL) NOPASSWD: ALL'
        dest: /etc/sudoers.d/wheel
        mode: '0400'
        owner: root
        group: root
    - name: Add user antti
      ansible.builtin.user:
        name: antti
        password: $6$AGa1f5P0XzaHiqeg$qkhjY9T1FMQPnObqRZOgmfFB7GZym615vn5i1ccV3CpW2NSAOge4zmvwL6H5F43zBKXgMoWfLJoAsj6Ku2SSE1
        shell: /bin/zsh
        append: yes
        groups: "wheel"
    - name: Remove bashrc
      ansible.builtin.file:
        path: /home/antti/.bashrc
        state: absent
    - name: Remove bash_profile
      ansible.builtin.file:
        path: /home/antti/.bash_profile
        state: absent
    - name: Remove bash_logout
      ansible.builtin.file:
        path: /home/antti/.bash_logout
        state: absent
    - name: Create i3 config directory for antti
      ansible.builtin.file:
        path: /home/antti/.config/i3
        state: directory
        owner: antti
        group: antti
        mode: '0755'
        recurse: yes
    - name: Change default shell to Zsh
      become: yes
      shell: chsh -s $(which zsh) antti
    - name: Clone yay
      become_user: vagrant
      git:
        repo: https://aur.archlinux.org/yay-bin.git
        dest: "/tmp/yay"
        update: true
    - name: Build and install yay
      become_user: vagrant
      command:
        chdir: "/tmp/yay"
        cmd: "makepkg -sfi --noconfirm"
        creates: /usr/bin/yay
