---
  - name: "Setup ArchLinux developing environment"
    become: yes
    hosts: archlinux

    tasks:
    - name: Remove virtualbox nox utils
      community.general.pacman:
        name:
          - virtualbox-guest-utils-nox
        state: removed
        update_cache: true
    - name: Install base packages
      community.general.pacman:
        name:
          - neovim
          - git
          - base-devel
          - zsh
          - xorg-server
          - xorg-xinit
          - xf86-video-vmware
          - i3-gaps
          - i3status
          - xfce4-terminal
          - rofi
          - starship
          - noto-fonts-emoji
          - xsel
          - httpie
          - ttf-jetbrains-mono
          - ripgrep
          - bat
          - exa
          - virtualbox-guest-utils
          - curl
          - sudo
          - fakeroot
          - which
        state: latest
        update_cache: true
    - name: Enable virtualbox service
      ansible.builtin.service:
        name: vboxservice
        state: started
    - name: Modify sudoers file
      ansible.builtin.copy:
        content: '%wheel ALL=(ALL) NOPASSWD: ALL'
        dest: /etc/sudoers.d/wheel
        mode: '0400'
        owner: root
        group: root
    - name: Add user antti
      ansible.builtin.user:
        name: antti
        password: $6$AGa1f5P0XzaHiqeg$qkhjY9T1FMQPnObqRZOgmfFB7GZym615vn5i1ccV3CpW2NSAOge4zmvwL6H5F43zBKXgMoWfLJoAsj6Ku2SSE1
        shell: /bin/zsh
        append: yes
        groups: wheel
    - name: Remove bashrc
      ansible.builtin.file:
        path: /home/antti/.bashrc
        state: absent
    - name: Remove bash_profile
      ansible.builtin.file:
        path: /home/antti/.bash_profile
        state: absent
    - name: Remove bash_logout
      ansible.builtin.file:
        path: /home/antti/.bash_logout
        state: absent
    - name: Create config directory for antti
      ansible.builtin.file:
        path: /home/antti/.config/i3
        state: directory
        owner: antti
        group: antti
        mode: '0755'
        recurse: yes
    - name: Create terminal config directory for antti
      ansible.builtin.file:
        path: /home/antti/.config/xfce4/terminal
        state: directory
        owner: antti
        group: antti
        mode: '0755'
        recurse: yes
    - name: Create local bin directory
      ansible.builtin.file:
        path: /home/antti/.local/bin
        state: directory
        owner: antti
        group: antti
        mode: '0755'
    - name: Copy user dotconfig files
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /home/antti/
        owner: antti
        group: antti
        mode: u+rw,g-wx,o-wx
      with_fileglob:
        - config/dotfiles/.*
    - name: Copy wm config files for user
      ansible.builtin.copy:
        src: config/i3.config
        dest: /home/antti/.config/i3/config
        owner: antti
        group: antti
        mode: u+rw,g-wx,o-wx
    - name: Copy terminal config files for user
      ansible.builtin.copy:
        src: config/terminalrc
        dest: /home/antti/.config/xfce4/terminal/
        owner: antti
        group: antti
        mode: u+rw,g-wx,o-wx
    - name: Copy starship config files for user
      ansible.builtin.copy:
        src: config/starship.toml
        dest: /home/antti/.config/
        owner: antti
        group: antti
        mode: u+rw,g-wx,o-wx
    - name: Copy goto for user
      ansible.builtin.copy:
        src: bin/goto.sh
        dest: /home/antti/.local/bin/
        owner: antti
        group: antti
        mode: u+rw,g-wx,o-wx
    - name: Install Oh-My-Zsh
      become_user: antti
      git:
        repo: https://github.com/robbyrussell/oh-my-zsh.git
        dest: ~/.oh-my-zsh
        clone: yes
      register: oh_my_zsh_result
    - name: Change default shell to Zsh
      become_user: antti
      shell: chsh -s $(which zsh)
      when: oh_my_zsh_result.changed == true
    - name: Clone yay
      become_user: vagrant
      git:
        repo: https://aur.archlinux.org/yay-bin.git
        dest: "/tmp/yay"
        update: true
    - name: Build and install yay
      become_user: vagrant
      command:
        chdir: "/tmp/yay"
        cmd: "makepkg -sfi --noconfirm"
        creates: /usr/bin/yay
