---
- name: Install base packages
  community.general.pacman:
    name:
      - neovim
      - git
      - base-devel
      - zsh
      - xorg-server
      - xorg-xinit
      - i3-wm
      - i3status
      - wezterm
      - rofi
      - xsel
      - httpie
      - ripgrep
      - bat
      - exa
      - curl
      - sudo
      - fakeroot
      - ttf-jetbrains-mono-nerd
      - noto-fonts-emoji
      - unzip
      - lazygit
      - fd
      - btop
      - chezmoi
      - fzf
      - zoxide
      - starship
    state: latest
    update_cache: true

- name: Ensure a locale exists
  community.general.locale_gen:
    name: "{{ item }}"
    state: present
  with_items:
    - en_US.UTF-8
    - et_EE.UTF-8

- name: Clone yay repository
  ansible.builtin.git:
    repo: "https://aur.archlinux.org/yay.git"
    dest: "/home/vagrant/yay"
    clone: yes
    update: no
    force: yes
    version: "master"

- name: Change ownership of yay directory to vagrant
  ansible.builtin.command: chown -R vagrant:vagrant /home/vagrant/yay

- name: Build and install yay
  ansible.builtin.shell: |
    cd /home/vagrant/yay
    makepkg -si --noconfirm
  args:
    chdir: /home/vagrant/yay
  become: yes
  become_user: vagrant

